--- #YAML:1.0
name:               Paranoid
version:            0.24
abstract:           General function library for safer, more secure programming
author:
    - Arthur Corliss <corliss@digitalmages.com>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    Carp:        0
    Errno:       0
    Fcntl:       0
    File::Glob:  0
    Test::More:  0
    Test::Pod:   0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.46
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
